In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Create dataset (10 rows, 3 parameters)
data = {
    "Hours_Studied": [2, 4, 6, 8, 10, 3, 7, 5, 9, 1],
    "Projects_Completed": [1, 2, 3, 4, 5, 2, 4, 3, 5, 1],
    "Internships": [0, 1, 1, 2, 2, 0, 2, 1, 2, 0],
    "Salary": [20, 35, 50, 65, 80, 30, 70, 55, 75, 15]
}

df = pd.DataFrame(data)
df


,Hours_Studied,Projects_Completed,Internships,Salary
0,2,1,0,20
1,4,2,1,35
2,6,3,1,50
3,8,4,2,65
4,10,5,2,80
5,3,2,0,30
6,7,4,2,70
7,5,3,1,55
8,9,5,2,75
9,1,1,0,15


In [ ]:
# Independent variables
X = df[["Hours_Studied", "Projects_Completed", "Internships"]].values

# Add intercept column (1s)
X = np.c_[np.ones(len(X)), X]

# Dependent variable
y = df["Salary"].values.reshape(-1,1)

X, y


(array([[ 1.,  2.,  1.,  0.],
        [ 1.,  4.,  2.,  1.],
        [ 1.,  6.,  3.,  1.],
        [ 1.,  8.,  4.,  2.],
        [ 1., 10.,  5.,  2.],
        [ 1.,  3.,  2.,  0.],
        [ 1.,  7.,  4.,  2.],
        [ 1.,  5.,  3.,  1.],
        [ 1.,  9.,  5.,  2.],
        [ 1.,  1.,  1.,  0.]]),
 array([[20],
        [35],
        [50],
        [65],
        [80],
        [30],
        [70],
        [55],
        [75],
        [15]]))

In [ ]:
# Normal equation
beta = np.linalg.inv(X.T @ X) @ X.T @ y

beta


array([[ 6.2],
       [-0.2],
       [12.6],
       [ 6. ]])

In [ ]:
print("Regressor Equation:")
print(f"Salary = {beta[0][0]:.3f} + {beta[1][0]:.3f}(Hours) + {beta[2][0]:.3f}(Projects) + {beta[3][0]:.3f}(Internships)")


Regressor Equation:
Salary = 6.200 + -0.200(Hours) + 12.600(Projects) + 6.000(Internships)


In [ ]:
y_pred = X @ beta
y_pred


array([[18.4],
       [36.6],
       [48.8],
       [67. ],
       [79.2],
       [30.8],
       [67.2],
       [49. ],
       [79.4],
       [18.6]])

In [ ]:
n = len(y)

# Mean Squared Error
mse = np.sum((y - y_pred)**2) / n

# Root MSE
rmse = np.sqrt(mse)

# Mean Absolute Error
mae = np.sum(np.abs(y - y_pred)) / n

# R-squared
ss_total = np.sum((y - np.mean(y))**2)
ss_residual = np.sum((y - y_pred)**2)

r2 = 1 - (ss_residual / ss_total)

print("MSE:", mse)
print("RMSE:", rmse)
print("MAE:", mae)
print("R2 Score:", r2)


MSE: 8.799999999999994
RMSE: 2.966479394838264
MAE: 2.4800000000000084
R2 Score: 0.982122905027933


In [ ]:
new_x = np.array([[1, 6, 3, 1]])
predicted_salary = new_x @ beta

print("Predicted Salary (Multiple Regression):", predicted_salary[0][0])


Predicted Salary (Multiple Regression): 48.79999999999869


In [ ]:
X_poly2 = df[["Hours_Studied", "Projects_Completed", "Internships"]].values

h = X_poly2[:,0]
p = X_poly2[:,1]
i = X_poly2[:,2]

X2 = np.column_stack([
    np.ones(len(h)),
    h, p, i,
    h**2, p**2, i**2,
    h*p, h*i, p*i
])

y = df["Salary"].values.reshape(-1,1)

X2.shape


(10, 10)

In [ ]:
beta2 = np.linalg.inv(X2.T @ X2) @ X2.T @ y
beta2


array([[-3.46078424e+13],
       [ 1.21428590e+13],
       [-1.69742073e+13],
       [-4.91868817e+12],
       [ 2.03659958e+12],
       [ 9.46374536e+12],
       [-1.89512715e+01],
       [-8.86244992e+12],
       [ 5.16796800e+00],
       [ 5.89465317e+01]])

In [ ]:
y_pred2 = X2 @ beta2

mse2 = np.sum((y - y_pred2)**2) / len(y)
rmse2 = np.sqrt(mse2)
mae2 = np.sum(np.abs(y - y_pred2)) / len(y)

ss_total2 = np.sum((y - np.mean(y))**2)
ss_residual2 = np.sum((y - y_pred2)**2)

r2_2 = 1 - (ss_residual2 / ss_total2)

print("Degree 2 Metrics")
print("MSE:", mse2)
print("RMSE:", rmse2)
print("MAE:", mae2)
print("R2:", r2_2)


Degree 2 Metrics
MSE: 5.944333795222361e+26
RMSE: 24381004481403.88
MAE: 23325237222726.01
R2: -1.2075843159415665e+24


In [ ]:
X3 = np.column_stack([
    np.ones(len(h)),
    h, p, i,
    h**2, p**2, i**2,
    h**3, p**3, i**3,
    h*p, h*i, p*i
])

X3.shape


(10, 13)

In [ ]:
beta3 = np.linalg.inv(X3.T @ X3) @ X3.T @ y
beta3


array([[ 3.50083008e+02],
       [ 8.59390259e+00],
       [-3.16699219e+01],
       [-1.44248810e+02],
       [-9.98886108e+00],
       [-8.15917969e+00],
       [ 4.53271484e+01],
       [ 2.25080884e-01],
       [-2.07962036e+00],
       [-1.19384766e+01],
       [ 2.46331787e+01],
       [-5.00000000e+00],
       [ 1.50146484e+01]])

In [ ]:
y_pred3 = X3 @ beta3

mse3 = np.sum((y - y_pred3)**2) / len(y)
rmse3 = np.sqrt(mse3)
mae3 = np.sum(np.abs(y - y_pred3)) / len(y)

ss_total3 = np.sum((y - np.mean(y))**2)
ss_residual3 = np.sum((y - y_pred3)**2)

r2_3 = 1 - (ss_residual3 / ss_total3)

print("Degree 3 Metrics")
print("MSE:", mse3)
print("RMSE:", rmse3)
print("MAE:", mae3)
print("R2:", r2_3)


Degree 3 Metrics
MSE: 39382.32389280984
RMSE: 198.4498019470159
MAE: 168.2294693815983
R2: -79.00472096050756


In [ ]:
# New input
h_new = 6
p_new = 3
i_new = 1

# Degree 2 prediction
new_x2 = np.array([[1,
                    h_new, p_new, i_new,
                    h_new**2, p_new**2, i_new**2,
                    h_new*p_new, h_new*i_new, p_new*i_new]])

pred2 = new_x2 @ beta2

# Degree 3 prediction
new_x3 = np.array([[1,
                    h_new, p_new, i_new,
                    h_new**2, p_new**2, i_new**2,
                    h_new**3, p_new**3, i_new**3,
                    h_new*p_new, h_new*i_new, p_new*i_new]])

pred3 = new_x3 @ beta3

print("Predicted Salary (Degree 2):", pred2[0][0])
print("Predicted Salary (Degree 3):", pred3[0][0])


Predicted Salary (Degree 2): -18624803801219.465
Predicted Salary (Degree 3): 213.65378696232978
